#!/bin/sh

# get the message and get the file 
msg=$(git log --pretty=oneline -1)
files=$(git log --pretty="format:" --name-only -1)

g++ myProg.cpp -o myProg
./myProg -e "$GIT_AUTHOR_EMAIL" -n "$GIT_AUTHOR_NAME" -d "$GIT_AUTHOR_DATE" -m "$msg" -f "$files"

# put it on the wiki, only a test environment

echo "This is a test commit" >> test.txt
git wiki add Home.md
git wiki commit -m "commiting"
git push wiki master
