#!/bin/sh

msg=$(git log --pretty=oneline -1)
files=$(git log --pretty="format:" --name-only -1)

g++ myProg.cpp -o myProg
./myProg -e "$GIT_AUTHOR_EMAIL" -n "$GIT_AUTHOR_NAME" -d "$GIT_AUTHOR_DATE" -m "$msg" -f "$files"
