callDatabase.o: .git/GitHook-master/scripts/callDatabase.cpp
	g++ .git/GitHook-master/scripts/callDatabase.cpp -o .git/GitHook-master/scripts/callDatabase --std=c++11 -lmysqlclient
	.git/GitHook-master/scripts/callDatabase -e ross.kaplan96@gmail.com -n Jerk McJerkyface -d 1480919509 -0500 -m a5dbc68616b0bf7ea48b8175dcebbe118d40542a *tag1test* *tag2test* test message here -f test test2

